---

dist: xenial
sudo: required

# Install requirements
install:
  - apt-get install -y python pip
  - pip install -r requirements.txt

# Test all the scenarios against the Ansible versions defined in the tox.ini file
script:
  - tox

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
