---

- name: run the main roles
  hosts: all
  roles:
    - role: AerisCloud.disk
      disk_additional_disks:
        - disk: /dev/vdb
          fstype: xfs
          mount_options: defaults
          mount: /example
          disable_periodic_fsck: false
      become: yes
